apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: kplabs-update
  name: kplabs-update
spec:
  replicas: 2
  selector:
    matchLabels:
      run: kplabs-update
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: kplabs-update
    spec:
      containers:
      - image: nginx2:alpine
        name: kplabs-update
        resources: {}
status: {}
