apiVersion: v1
kind: Pod 
metadata:
  labels:
    run: readiness
  name: readiness
spec:
  containers:
  - image: nginx
    name: readiness
    ports:
    - containerPort: 80
    readinessProbe:
      tcpSocket:
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 5
